name: Swagger to HTML

on:
  push:
    branches:
      - main # Или ваша рабочая ветка

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    
    - name: Generate HTML from Swagger YAML
      run: |
          wget https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.0/swagger-codegen-cli-3.0.0.jar
          java -jar swagger-codegen-cli-3.0.0.jar generate -i oop_doctors_help/node-output -l html2 -o oop_doctors_help/node-output

    - name: Commit HTML files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add oop_doctors_help/node-output/*.html
        git commit -m "Update HTML documentation" || echo "No changes to commit"
        git push
