name: Swagger Sync and HTML Generation
on:
  push:
    branches:
      - swaggerhub

jobs:
  generate-and-push-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Generate HTML from Swagger YAML
        run: redocly bundle swagger.yaml --output ./node-output/index.html

      - name: Commit HTML file
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add ./node-output/index.html
          git commit -m "Update HTML documentation" || echo "No changes to commit"
          git push
